package com.askme.astronov.utils.Enums;


public enum EventType {

    SENDING_OUTGOING_REQUEST,
    RECEIVED_INCOMING_REQUEST,
    RESPONSE_TO_INCOMING_REQUEST,
    RECEIVED_SUCCESSFUL_REQUEST,
    SENDING_INCOMING_RESPONSE,
    RECEIVED_BAD_REQUEST,
}
