server:
  port: 8081

spring:
  application:
    name: astronov
  # liquibase properties
  liquibase:
    change-log: db/changelog/master.xml
  # database properties
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mask:
  fields:
    - Authorization